### ISSUE TITLE
Doesn't open output doc. or calculate a solution

### ISSUE THREAD

**Issue by rkeller6** [astropcr/pmasecapstone#21] opened 2016-07-23 23:36 UTC
[disasterTradeStudyLog.txt](https://github.com/astropcr/pmasecapstone/files/380020/disasterTradeStudyLog.txt)

**Comment by mrozbarrett** [comment] 2016-07-24 00:54
Does not open output file when debris, smoke and dust, ground instability, and ash are selected.

**Comment by mrozbarrett** [comment] 2016-07-24 00:55
Think that it has to do with ash, if only ash is selected as a disaster effect, the word doc report does not generate.

**Comment by rkeller6** [comment] 2016-07-24 01:17
My problem was a keyboard actuator error...  please disregard my log file.

**Comment by mrozbarrett** [comment] 2016-07-24 01:38
It looks like it may be an issue when new rows are added to the databases.  Using original files with same filters allows file to be opened. New matrices are in the solution design folder (originals are in archive folder inside solution design folder)

**Comment by fuzzynickel** [comment] 2016-07-24 02:43
Was able to get a Word file output with only ash selected.  No clue as to why.  Another datapoint.
[disasterTradeStudyLog.txt](https://github.com/astropcr/pmasecapstone/files/380068/disasterTradeStudyLog.txt)

[DRTS-Results-2016-07-23-22-38-37-81517725.docx](https://github.com/astropcr/pmasecapstone/files/380065/DRTS-Results-2016-07-23-22-38-37-81517725.docx)

**Comment by astropcr** [comment] 2016-07-24 02:59
Also able to get the file to work with just Ash.

**Comment by fuzzynickel** [comment] 2016-07-24 03:08
Was able to reproduce the problem.

![image](https://cloud.githubusercontent.com/assets/20302156/17081500/f3590bcc-5129-11e6-9b54-9a5519e4cd02.png)

[disasterTradeStudyLog.txt](https://github.com/astropcr/pmasecapstone/files/380086/disasterTradeStudyLog.txt)

**Comment by astropcr** [comment] 2016-07-24 03:58
@mrozbarrett report this is fixed. Katie error perhap and the issue fixed in

**Closed as completed** 2016-07-24 03:58 UTC
Labels: show-stopper-bug
